### ISSUE TITLE
Data sources

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [smarco/BiWFA-paper#1]
Hi! Nice to see this out in the open! Looks like some nice results, so I will now replace WFA and variants with just BiWFA in my evals.

Since you now also test on longer sequences, I'd again like to run on the same data.
I see you posted a set of instructions to run the evals given the data, but I don't see links to the original data sources, and your paper doesn't contain any accession numbers.

For purposes of reproducability and efficiency, I would much appreciate if you could again share your input data, ideally with some scripts to generate them from raw downloads. (I'm completely inexperienced with any kind of data manipulation tools for fasta/sam files for now, so the probability of making a mistake while I try to reproduce your work is high.)

Also, could you provide a bit more details on the data? It would be nice to know the average error rate and model, and the average s for the two datasets, since this matters a lot for e.g. the relative performance of WFA and edlib (looking at the table in the WFA paper).

Cheers!

**Comment by smarco** [comment]
Thanks! We are happy to have this out.

> I will now replace WFA and variants with just BiWFA in my evals.

You have us all intrigued with your A* Pairwise Aligner. I'm really curious to see your results :-)

> For purposes of reproducability and efficiency, I would much appreciate if you could again share your input data [...]

I think that is a very sensible request. Let me synch with @AndreaGuarracino to see how we can share those files.

> Also, could you provide a bit more details on the data? It would be nice to know the average error rate and model, and the average s for the two datasets, since this matters a lot for e.g. the relative performance of WFA and edlib (looking at the table in the WFA paper).

That is a good idea. We will incorporate this information. Thanks for the feedback. 

Cheers,

PS. I'll go answer the other tickets, give me some time to process it all.

**Comment by AndreaGuarracino** [comment]
For the first dataset (the one generated by the Human Pangenome Reference Consortium) there are the same embargo issues you have already clashed against in `wfalm` preprint (https://github.com/jeizenga/wfalm/issues/6).

Regarding the ONT MinION reads from Bowden et al. (2019), restricted to those at least 500 kbp long, I've just shared them at https://github.com/smarco/BiWFA-paper/blob/main/evaluation/data/ONT_MinION_UL.500kbps.zip. Have fun (but don't destroy us)!

**Comment by RagnarGrootKoerkamp** [comment]
Wow, thanks a lot! I just did our first run on long reads, and you don't have to worry -- we're around 30x slower for now (`6s` vs `170s` on `seq1.seq`, and `5s` vs `140s` on `seq25.seq`), when running BiWFA for unit edit costs.

I was looking at the generated CIGAR a bit, and it seems that both of these pairs at some point contain a deletion of a few thousand long. In more detail: `seq25.seq` has a deletion of size roughly `2100` somewhere just over halfway of the length it seems. This completely destroys our performance, since we depend on errors being uniformly distributed for good runtime. If I only run on the first half, it only takes around `2s`, so comparable to you :)

Anyway, this somewhat contradicts my assumption that ONT sequencing errors are actually uniform -- I wasn't expecting such long deletions as all. (Or maybe the sequenced data does not directly correspond to the reference and we're actually looking at biological mutations here? I'll have to look into this.)

**Comment by ekg** [comment]
Fwiw, Long indels in ONT data are typically biological.

**Comment by AndreaGuarracino** [comment]
@RagnarGrootKoerkamp, if you find sequence pairs or new cases where BiWFA is slower than your approach, please send them to us. The challenge is now publicly open :imp:

**Comment by RagnarGrootKoerkamp** [comment]
I think (hope) you should be able to run my evals so you can see for yourself, if you're up for a potential challenge (1, to get it running, and 2, to be faster;) Let me quickly explain here. (I have to write a readme and such, but the paper has priority now; it's been too long already.)

1. Clone the [repo](https://github.com/RagnarGrootKoerkamp/astar-pairwise-aligner).
2. `cd evals`
3. `cargo build --release; cargo build --release --example generate_dataset`
   (you need rust for this; see https://rustup.rs to install it.)
4. edit the `Snakemake` file and under `TOOL DEFINITIONS` change the path to your `biwfa` binary.
5. a bit further down remove `edlib` from `tools = ...`. (I have a local version that takes `.seq` files. Will push eventually.)
6. Run `snakemake table/tools_N1e5.tsv -j 4`. This will a) generate uniform random input, b) run A*PA and WFA on it and benchmark them, c) collect the results in the table provided. Change the `5` to a `6` or `7` to run on larger data. (`7` will take some hours).

You can also manually invoke `cargo run --release --example generate_dataset -- --help` to generate random `.seq` files.

Run our tool manually as `cargo run --release -- -i ./evals/input/synthetic/x1000-n1000-e0.05.seq --error-rate 0.05 [-s]`. `--error-rate` is needed to choose reasonable parameters up front.

For sequences of error rate `5%` and length at least 10k, we should be faster.

Actually, there are already some [tables](https://github.com/RagnarGrootKoerkamp/astar-pairwise-aligner/blob/ce869555393e797e9d847fe83aa2d6dc76e2a613/evals/table/tools_N1e7.tsv) committed in `evals/table/`, that should speak for themselves, and you could check the [evals/evals.py](https://github.com/RagnarGrootKoerkamp/astar-pairwise-aligner/blob/master/evals/evals.ipynb) notebook for some figures.

For completeness, let me note here again that we're faster, but that's only because the pairs we generate have uniform errors. Change the [`--model`](https://github.com/RagnarGrootKoerkamp/astar-pairwise-aligner/blob/ce869555393e797e9d847fe83aa2d6dc76e2a613/src/generate.rs#L10) on the `generate_dataset` tool to make long indels instead.
