### ISSUE TITLE
Possible bug in Algorithm 1

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [smarco/BiWFA-paper#8]
Hey @smarco @ekg ,

I was implementing BiWFA myself, and as expected I re-discovered most of the technical details you mention in section 2.3 :smile:  :see_no_evil:.

One particular test case that I ran into is the following (first a conceptual explanation, then an example):

**Conceptual case**:

Suppose the mismatch cost is `x=1`, and the gap cost is `e=10`, without open cost (`o=0`).

The optimal path `A` has length 100, with an indel in the middle, from `s_f=45` to `s_f=55`.
This path is found after expanding `s_f=s_r=55` from the start and end.

There is also a suboptimal path `B` of length `101` with a substitution in the middle, from `s_f=50` to `s_f=51`. This path is found after expanding `s_f=51` from the start and `s_r=50` from the end.

In `Algorithm 1` in the paper, you run `BIWFA_BREAKPOINT` while `s_f + s_r - o < s_b`. Path `B` will match af `s_f=51` and `s_r=50`, giving `s_b=101`. At this point, further increasing either `s_f` or `s_r` will terminate the algorithm.
However, the optimal path `A` of cost `100` is only found at `s_f = s_r = 55`.

**Example**:

`x=1`, `o=0`, `e=3`:
seqs:
```
CGC
CACG
```

The exact alignment cost is `4` via `1M1X1M1I`, where the meeting is at `s_f = 1`, `s_r = 3`.

My implementation of BiWFA, when iterating till `s_f+s_r-o<s_b` finds cost `5` via `1M1I2X` at `s_f = 3` and `s_r = 2`.

**Resolving it**:
Simply iterating while `s_f + s_r - p < s_b` (where `p=max(x, o+e)`) should resolve this, which also corresponds to section `2.3`.

~Actually, I think it is sufficient to iterate while `s_f + s_r - floor(p/2) < s_b`, but this would require a bit more formal argumentation.~ No that's probably not true; increasing both `s_f` and `s_r` by `p/2` is already captured by doing `-p`.

**Conclusion**
Two things were wrong:
- The paper was indeed missing the extra `-p` in the check to terminate. The code already had it though.
- I was testing BiWFA without explicitly disabling heuristics, which made it give wrong results on large inputs.

**Comment by RagnarGrootKoerkamp** [comment]
Regarding the proof, lemma 2.1 looks fine, but the sentence below it,

> Moreover, if the first of the three conditions is found to hold for some values `s_f` and `s_r`, then `s_opt <= s_f + s_r + s_o`.

is weird to me. Once you find _some_ path of length `s_f + s_r = s`, 'clearly' the optimal path has cost less than `s_f + s_r + o`.

The second bullet point,

> Algorithm 1 continues for `o` additional iterations after finding some `s_f` and `s_r` that satisfy the overlap condition.

isn't really motivated currently, which may explain the bug.

I wrote up a sketch for a new proof here: https://research.curiouscoding.nl/posts/diagonal-transition-meeting-condition/
(Turns out github supports latex, but not sufficiently to make it readable :/)

From this, we actually need to continue while $s_f + s_r < s_b + o + p$, which is even more than the bound of $s_f + s_r < s_b + p$ I was assuming in my previous post.

Once I have a working implementation of BiWFA with affine costs, I'll run some tests on this.

**Comment by jeizenga** [comment]
I'm pretty sure it's correct as is. Once you find any solution, you get `s_r + s_f <= s_{opt} <= s_f + s_r + o` for the current values of `s_f` and `s_r`, because one of the three conditions stated in the lemma must hold. The necessity for only `o` additional iterations follows pretty immediately.

**Comment by RagnarGrootKoerkamp** [comment]
I agree with `s_{opt} <= s_f + s_r + o`, but my example is a counter example against `s_f + s_r <= s_{opt}`.
In particular, it finds a first solution at `s_f + s_r = 3+2=5`, but the optimal solution is at `s_{opt} = s'_f + s'_r = 1+3=4 < 5`.

I think I am misunderstanding something in your upper bound: once you find any solution at the current `s_f` and `s_r`, the cost of that solution is less than `s_f + s_r`, and hence the cost of the optimal solution also satisfies `s_{opt} <= s_f + s_r`, so the `+o` doesn't seem useful to me. I'm parsing 'current values of `s_f` and `s_r`' as 'at the time of finding the first / any solution'. Maybe you mean something else?

**Comment by RagnarGrootKoerkamp** [comment]
Hmm, I think I have an off-by-one in my interpretation of the upper bound `s_f+s_r-o<s_b`: I was thinking you first increment `s_f` / `s_r` and then check the bound, but in your pseudocode you first check `s_f + s_r - o < s_b` and only then do you increment one of the two.

Either way, that can be worked around by doubling all costs in the example.

**Comment by jeizenga** [comment]
I'm looking over this again more carefully, but I think I'm still not understanding something. In your example, the second set of scores (`s_f = 3` and `s_r = 2`) should never replace the original meeting (`s_f = 1` and `s_r = 3`) because the score is `s_f + s_b - o = 3 + 2 - 0 = 5`, which is higher than the original score of 4. You need to continue for the `o` additional iterations to ensure that you see `s_{opt}`, but you wouldn't supersede your first meeting point with a less-optimal meeting point.

**Comment by RagnarGrootKoerkamp** [comment]
Let me work out the example a bit more.
We have `A = CGC`, `B = CACG`, `x=1`, `o=0` and `e=3`.
First, here is a gif of what's happening, with the forward and reverse front alternatingly expanding:

![biwfa](https://user-images.githubusercontent.com/6233682/178471087-72a58f72-07bb-4641-a05e-1903f19ce7dc.gif)

Let's go over the steps:
`s_f = 0`: (blue)
The first characters `C=C` match, so `M_f(0,0) = 1`.
`s_r = 0`: (green)
The last characters`C/G` do not match, so `M_r(0,0) = 0`.
`s_f = 1`: (lime)
After paying for the mismatch `G/A` there is a match `C=C`, so `M_f(1, 0) = 3`.
`s_r  = 1`: (yellow)
The reverse front is extended by one (`G/C`).
`s_f = 2`:
This step is not visible. The main diagonal is extended outside the grid. Note that cost is not yet enough to make an indel.
`s_r = 2`: (orange)
The reverse front is extended by one more.
`s_f = 3`: (red)
At this point, the cost is large enough for indels. From the forward `s_f=0` layer (blue) we can make an insertion or deletion. The main diagonal is also extended, but again this is out of the bounds of the figure.
Note that the lower red cell overlaps the orange cell of the backward front. This means that at this point, we find a first path, at `s_f = 3` and `s_r = 2`. Thus, we set `s_b = 5`.

Now, we check whether `s_f + s_r - o >= s_b`. In this case, `3+2-0>=5` is indeed the case, and hence the algorithm stops.

If we were to continue one extra step however, the following would happen:

![biwfa_fixed](https://user-images.githubusercontent.com/6233682/178471106-0193af6c-a1a1-425e-884a-c66237c3bcd1.gif)

We go to `s_b = 3`, and obtain the dark red front.
This overlaps with the lime forward `s_f=1` front, and we find a path of cost `4`, less than the cost `5` path found before.

**Comment by jeizenga** [comment]
Ahh ok, I see your point. We should definitely fix this in the submitted version. I should also flag @smarco to see if this is a bug in the actual code too.

Thanks for the catch!

**Comment by RagnarGrootKoerkamp** [comment]
Here's an input on which BiWFA (using `WFA2-lib` with `ultralow` memory) gives a wrong output, assuming my own scoring (simply NW's algorithm as a baseline) is correct:

Scoring model: `x=1`, `o=0`, `e=10`.
The score should be `456`.
You return `479`.

Note that for most samples I find, you are off by less than `10` in this case, but in this particular case the difference is more than `10`, which may be because I'm running in full-path mode, not score-only mode.

```
<CGCAACTGCAATCGGGAGTCAGTTCAGTAACAAGCGTACGACTATTCTTTCCCACGCAGGGACTATTTTAGGCGGTGCCCGGAGACTGAGAACCCGGTGAACACATCGCGTAACCCTGACTGTAGCAACACCCTCTGCCTCTACCCGCAAGCAAATAACGACGACCATCGGACCGCAGACCAGGTCGTGATACCTGCAAAAATTCGATGAGACGCTACAGTGGCTGGACAGCGCATTCAGAATCTTACATTCGTCGCCGATGACATCACTCGTTGCTAATAGCGGTGTACCTTTTCACCCACAACTATACGCCAAATTCCGGCGTGATAGTGCACTTGTGCTTCGGCCAACACTAGACGTAACCCGAACCGTAACAAGCCGGTGTGCGCGTCCAACGGCATGTGCTCTGTTGCGTCAAACACGACTTTTGGCTCTATCCATAGCCTGTCGCACCGACCTGCACATCGACTTAGCCCATAACCCTCTCTTAGTATGGAGAGAGAAAAGTGGTGAGTCCTCTATATTCTATAGCCTTTACTTCGGCCCCTCCCTGATTATCTGACGTTAGTATCGCTGCCTTCTAAATCAAACCTCGTGATGAACGTGGCCACAACTGGTTTAGCCGGTGTTCGAAAATTACCTTGAAATCTT
>CGCACGTGCAATGGCGGAATGCAAATACATAAAAAGCAGCTAGCACGCTTCTTGCCCCCTCAGGGTTAACTACTTGTAGGCGTGCCCTGGAGACTGAGAATCCGGTGAATCACTTCAGCTGAACCCTGCCTGTAAGCATACCTCCCGCCTGCTACCCACAGCAGATTACGAACGACAGCAACGGAGCAGGCGGACAGCCGTGGGTAATGCCATAAATCGGATAGACACGCTAGTGGGGACCCAACATTCAGAATCTTACATTCGCCGCCGATGCGATTAAGCTTGTTGATATAGCGGTGTCCTATTACCACACAATCAACGGCCCATCCGGTCGAGCCTGGTATTGTGCTCGTGCCAACATTATACTTGGCCGATGCCGGACAATGGCGCGTGTTTTGCATACGCAACGGGATGGCTCATTGCGGTCAACACGACTTTGGGCTCTTATCAAACTACGCACCGACTGCACATCATCTCTTAGCCCAAATCCCATCTCTTAGTATGGAGGAATGAGAAATTGGTGAGTCTCTGTAATGGCTATAAGCCTTACTTCGGCCCCCCTCTGATCTATCTGAGTGTAACGCTGCTTCTAAATCAACCTCCGTAATGTACGGGGCCACAGACGGTCTAGGGCGTTTGTTGACAAACCAGAATCATT
```

The fuzzing code is [here](https://github.com/RagnarGrootKoerkamp/astar-pairwise-aligner/blob/master/src/aligners/wfa.rs#L311).
The call to WFA is [here](https://github.com/RagnarGrootKoerkamp/astar-pairwise-aligner/blob/master/src/aligners/wfa.rs#L80).

**Comment by RagnarGrootKoerkamp** [comment]
Note: there are also cases where the difference between the actual distance and your returned distance is as large as 50 (still using mismatch=1, indel=10 linear costs). That can't really be explained by this bug as far as I see, and is not fixed by the PR above, so it is likely the implementation contains more bugs.

**Comment by smarco** [comment]
Sorry for the delay in answering here.

Thanks for the feedback, Ragnar. I had some time to review the case and, indeed, it is an error in the manuscript. Surprisingly (to me, at least), the algorithm in the manuscript did not reflect the implementation, which is based on the following condition.

 $s_f + s_r - p - o >= s_b$

Which can be found in the code as:

`min_score_forward + score_reverse - gap_opening >= junction->score`

I have checked both cases, and both return correct results using `BiWFA-paper` and `WFA2-lib` repositories.

So, I am not sure about the pull request. Perhaps you found another bug in the implementation. Can you double-check? I would appreciate it.

**Comment by RagnarGrootKoerkamp** [comment]
Ahh, I see now. I was confused about `min_score_forward` and `max_score_scope` before, but basically `max_score_scope` is $p$, and `min_score_forward` is $s_f - p$, so that indeed this gives the correct condition.

This explains the fact that my PRs did not actually fix the bug for me, so indeed it is likely the bug is something else. I don't really have a good idea of what the bug would be in that case though; would have to do some further investigation at a later point.

**Comment by smarco** [comment]
Is there a pair of sequences that I can use as example of the bug?

**Comment by RagnarGrootKoerkamp** [comment]
See a few comments up.

I've updated our [readme](https://github.com/RagnarGrootKoerkamp/astar-pairwise-aligner) with some installation instructions. If you don't mind installing Rust, you should be able to run
```
cargo test --features wfa --lib -- biwfa_fuzz --ignored
```
after making sure that the `wfa2` repo exists next to the A*PA repo (ie by doing `make wfa` in the root of the repo).

This gives an pair of broken sequences within a minute typically. (Currently it uses a fixed seed; you could comment that out and/or change the sequence length.)

**Comment by smarco** [comment]
It would be quicker if you could paste 1 example (e.g., just 1 pair of sequences and the penalties used) into this issue (it would help me a lot) :-)

**Comment by RagnarGrootKoerkamp** [comment]
See [here](https://github.com/smarco/BiWFA-paper/issues/8#issuecomment-1182668525) ;)

**Comment by smarco** [comment]
That one comes clean on both `BiWFA` and `WFA2-lib` repo ( $s_{opt}=-456$ ).

Can double-check if you have another example? Thanks!

**Comment by RagnarGrootKoerkamp** [comment]
Hmm yes, when using `align_benchmark` as
```
align_benchmark -i a.seq -o out --wfa-memory-mode ultralow --wfa-score-only --linear-penalties 0,1,10 -a gap-linear-wfa
```
where `a.seq` is as before it does give the right answer. But still calling `wavefront_align` via Rust is broken. I'm failing to see where the bug is so far.

**Comment by smarco** [comment]
But I thought the issue was using `gap-affine` distance; in which case:

```
./bin/align_benchmark -a gap-affine-wfa --input bug.seq -o bug.alg --wfa-memory-mode ultralow --affine-penalties=0,1,0,10
```

?

**Comment by RagnarGrootKoerkamp** [comment]
Ah no sorry. I'm simply doing linear costs here. But things are definitely weird on my side; simply calling normal WFA without BiWFA/memory-mode ultralow gives the same wrong answer via the API. Maybe I should try to call the API directly in C code and see if that changes anything.

**Comment by smarco** [comment]
So, It's an API problem? Rust or C++?

**Comment by RagnarGrootKoerkamp** [comment]
Rust. [this](https://github.com/RagnarGrootKoerkamp/astar-pairwise-aligner/blob/master/src/aligners/wfa.rs#L83-L105) is the code I'm using, which as far as I can see exactly mimics the instructions in the readme.

**Comment by smarco** [comment]
Disable heuristics (enabled by default):

`attributes.heuristic.strategy = wf_heuristic_none;`

**Comment by RagnarGrootKoerkamp** [comment]
Ahhhh, that explains things! All seems to be good now! Thanks for helping with debugging this!

My fuzztests don't seems to find any more inconsistencies now after a few minutes of running :smile:

**Comment by RagnarGrootKoerkamp** [comment]
Btw, you may want to mention this explicitly in the readme, a bit higher than just the heuristics section. Since the `align_benchmarks` tool is exact by default, and the examples don't mention it, I assumed the API would also be exact. It's not exactly clear which of the heuristics and what parameters are used by default now.

**Comment by smarco** [comment]
My concern here has always been the same. If I change it to `exact` by default everywhere (which I might), people will start running WFA2 default against their approximate methods (e.g., banded, x-drop, and whatnot) to conclude that they are 1000X faster than WFA. 

But I also see that it can be misleading to set it by default (with or without a note in the readme). 

No solution convinces me...

**Comment by RagnarGrootKoerkamp** [comment]
Yeah totally understandable. Personally I'd prefer the exact default, but for most practical usage a heuristic approach is likely more useful. Either way being explicit about this in the readme is a good idea.
