### ISSUE TITLE
Max antidiagonal optimization

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [smarco/BiWFA-paper#9]
Hey,

From your code it seems that you skip computing `WF_OVERLAP` when the furthest forward and backward antidiagonal do not reach each other yet. I think it's worth mentioning this in the paper -- I hadn't thought of it myself yet and it's a pretty simple optimisation that I may also put in my own code.

**Comment by smarco** [comment]
Hi,

Yes, indeed. I always tend to believe that this type of optimization details are not interesting for the community. But, if you find it useful, I can change my mind and add a note.

Thanks for the feedback.

**Comment by RagnarGrootKoerkamp** [comment]
Yeah, there is some vague balance between what is part of the algorithmic complexity and what is part of an efficient implementation. But this sounds pretty short to mention anyway.
